version: "3"

services:
  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.83.0-amd64
    command:
      - "--config"
      - /etc/otel/config.yml
    ports:
      - 4317:4317
    volumes:
      - ./config.yml:/etc/otel/config.yml
  jaeger:
    image: jaegertracing/all-in-one:1.48
    expose:
      - 14250
    ports:
      - 16686:16686
